version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Go task
          command: |
            mkdir /go/bin/task
            curl -s https://taskfile.org/install.sh | sh -s -- -d -b "/go/bin/task"
      - run:
          name: Building Docker image
          command: /go/bin/task/task docker:build
  release:
    docker:
      - image: circleci/golang:1.11.3
    steps:
      - checkout
      - run:
          name: Release
          command: curl -sL http://git.io/goreleaser | bash
  register:
    docker:
      - image: circleci/golang:1.11.3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Go task
          command: |
            mkdir /go/bin/task
            curl -s https://taskfile.org/install.sh | sh -s -- -d -b "/go/bin/task"
      - run:
          name: Push images to Docker hub
          command: /go/bin/task/task docker:push
workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - register:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
